// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MovieRecommenderML.Model
{
    public class ModelMovie
    {
        public float MovieId { get; set; }
        public string MovieName { get; set; }
    }
}
